/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zip4j.symlink;

import net.lingala.zip4j.ZipFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class App {
    public static void main(String[] args) throws IOException {
        final String path = App.class.getResource("/file.zip").getPath();
        final ZipFile zipFile = new ZipFile(path);
        final Path tempDirectory = Files.createTempDirectory("tmp");
        zipFile.extractAll(tempDirectory.toString());
    }
}
